---
title: "Summary Paper"
author: "Aniruddha Raghavendra" 
date: "2023-10-30"
output:
  html_document:
    toc: true
    toc_depth: 3
---

## Why this Topic?

Our team selected this topic due to its relevance and significance in today's health and fitness landscape. Understanding the factors that influence exercise patterns and calorie burn is crucial for promoting a healthy lifestyle and designing effective fitness programs. We were motivated to explore this topic to contribute valuable insights for individuals, fitness professionals, and health-related industries.

## Prior Research

Our research leverages prior studies in exercise science and health, diving into the complex relationships between exercise behavior, calorie burn, BMI, and weight management. By employing statistical methods like ANOVA, correlation analysis, and linear regression, we provide a comprehensive analysis. We aim to contribute valuable insights into how these factors interact and influence individual exercise choices and health outcomes.

## About the Dataset

The dataset used in this project, titled the "Exercise and Fitness Metrics Dataset," is a comprehensive collection of exercise and fitness-related information. It includes 12 variables, such as exercise type, calories burned, dream weight and so on. This dataset is a valuable resource for research in exercise science, fitness program development, and weight management analysis. It can also be used to study the correlations between exercise and health-related factors. The dataset offers insights into the relationships between various exercise variables, calorie expenditure, and weight-related measures, making it an essential tool for understanding the dynamics of exercise and fitness. You can access this dataset on Kaggle [here](https://www.kaggle.com/datasets/aakashjoshi123/exercise-and-fitness-metrics-dataset).

## Limitations of the Dataset

The dataset "Exercise and Fitness Metrics" provides valuable insights, but it does have limitations. One limitation is that it lacks information on dietary habits, which is crucial for a comprehensive understanding of weight-related measures. Additionally, more demographic details beyond age and gender, such as ethnicity, could offer a more nuanced analysis of the data. The dataset's sample size of 3864 entries may not fully represent all demographics, potentially leading to bias. Furthermore, detailed contextual information on exercise conditions, like gym equipment or outdoor settings, would enhance the dataset's utility. Collecting data on lifestyle factors, such as sleep patterns or stress levels, could also provide a more holistic perspective on health and fitness.

## SMART Questions

These SMART questions were formulated based on the dataset's variables and their relevance to exercise, fitness, and weight management. We aimed to create a well-rounded analysis by covering a range of factors, from age and gender differences in exercise preferences to the relationship between heart rate and BMI in achieving dream weight. These questions have practical applications, providing insights into optimizing exercise for specific goals. They enable us to explore trends over time, helping to identify changing exercise preferences and their impact on calorie expenditure and weight measurements. Overall, these SMART questions were designed to extract valuable, diverse, and actionable insights from the dataset, ensuring a holistic understanding of exercise and fitness metrics.

## After the EDA, did questions change? If so, how?

After the completion of the Exploratory Data Analysis (EDA), the two questions underwent refinement in order to more effectively correspond with the data insights and augment their analytical depth.

(Q4. Intital): Are there exercises more commonly performed indoors or outdoors, depending on the weather?\
(Q4. Updated): Which exercises are more popular in the different weather conditions?\
Reason: The initial question centered on a broad classification of exercises as indoor or outside based on the weather. However, EDA discovered that the popularity of specific exercises varies based on the weather. Hence, this question was revised to look at which workouts are preferred under varied weather conditions, resulting in a more nuanced understanding.

(Q5. Initial): Can the combination of heart rate and BMI be used to determine the optimal exercise duration?\
(Q5. Updated): Exercise Preference Across Different Durations and Frequency?\
Reason: The initial question sought to ascertain the optimum workout time in terms of both heart rate and body mass index. However, EDA revealed that people have different preferences for exercise durations and frequencies, independent of heart rate and BMI. Thus we, modified the question to delve deeper into these preferences, investigating the frequency and length of various exercises.

(Q6. Deleted): How closely do individuals' dream weights align with their actual weights? Reason: After the completion of the Exploratory Data Analysis (EDA), the question of the alignment of individuals' dream weights and actual weights was deleted.  This decision was made based on the observation that the output graph had a linear distribution, implying a high correlation between the two variables. A linearly distributed graph, from a data-centric standpoint, shows that there is little variability to explain or investigate further.

## What tests did you use? What were the results?

**1.) One-Way ANOVA:** This test conducted to investigate whether there is a significant difference in 'Calories Burn' across different 'BMI Classification' groups. The null hypothesis (H0) stated that the mean 'Calories Burn' is the same for all 'BMI Classification' groups, while the alternative hypothesis (H1) posited that at least one group has a different mean.

**One-Way ANOVA Results:**

-   The p-value was 0.509, greater than the 0.05 threshold, leading to a failure to reject the null hypothesis.

-   Post-Hoc Tukey HSD: This test also supported the ANOVA result, showing p-values greater than 0.05 for all pairwise comparisons between the groups.

**2.) Two-Way ANOVA:** In the analysis to evaluate the effects of 'Weather Conditions' and 'Exercise Intensity,' as well as their interaction, on heart rate. The assumptions for the test were validated using Shapiro-Wilk for normality and Levene's Test for homogeneity of variances.

**Two-Way ANOVA Results:**

-   For the effect of 'Weather Conditions': F=0.103,p=0.902F=0.103,p=0.902

-   For the effect of 'Exercise Intensity': F=0.942,p=0.487F=0.942,p=0.487

-   For the interaction effect: F=1.112,p=0.332F=1.112,p=0.332

## Interpreting the results

-   The One-Way ANOVA test was used to determine if there are significant differences in 'Calories Burn' across different 'BMI Classification' groups. The test yielded a p-value of 0.509, which is greater than the conventional alpha level of 0.05. This indicates that we fail to reject the null hypothesis, suggesting that the mean 'Calories Burn' is not significantly different across the BMI categories. The post-hoc Tukey HSD test corroborated this finding, as all pairwise comparisons between the groups also yielded p-values above 0.05.

-   The Two-Way ANOVA test was conducted to evaluate the effects of 'Weather Conditions' and 'Exercise Intensity,' as well as their interaction, on heart rate. All three p-values were above the 0.05 threshold, indicating a lack of statistical significance. Specifically, the p-values were 0.902 for 'Weather Conditions,' 0.487 for 'Exercise Intensity,' and 0.332 for their interaction. These results lead to the failure to reject the null hypotheses, suggesting that neither weather conditions nor exercise intensity significantly impact heart rate, and there is no interaction effect between them. This implies that other factors not captured in this model may influence heart rate.

## Final conclusions

This project aimed to answer five SMART questions regarding the impact of various variables from the dataset. Apart from these, we also used 'Weather Conditions,' 'Exercise Intensity,' and 'BMI Classification' on measurable outcomes such as heart rate and calories burned to build two statistical models: One-Way ANOVA and Two-Way ANOVA.

1.  **One-Way ANOVA**: The question about the influence of 'BMI Classification' on 'Calories Burn' was not supported by the data. The model effectively answered the question, revealing no significant influence of 'BMI Classification' on 'Calories Burn'.

2.  **Two-Way ANOVA**: This model addressed the complex interplay between 'Weather Conditions' and 'Exercise Intensity' on heart rate. The results indicated that neither these factors, nor their interaction, significantly impacted heart rate.

Both models paired with other visualizations provided clear data-driven answers to the SMART questions, demonstrating that, within the scope of this dataset, neither the weather conditions, exercise intensity, nor BMI classifications significantly influenced the measured target variable. This directs attention towards exploring other potential factors within this dataset.
